### ISSUE TITLE
*looking for more 👀*

### ISSUE THREAD

**Issue by AliAlmasi** [Azelliott/escape-from-amsterdam#1]
I ran the game. it was kinda good, as you said "best 3D engine is your own imagination".
But there's a little problem; I finished `chapter 1` but where's the continuation of the game?

**Comment by Azelliott** [comment]
Hi Ali, glad you kinda liked it 😄
There is no problem - if you check the source code, you will see that there's only "chapter one" done.

This was made just to practice making terminal interfaces so I decided to make a small game.
For now I have no plan in adding more due to lack of time/other projects.
